version: "3"
# services:
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"

# version: '3.8'
services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d
  proto:
    command: ./proto/scripts/protoc.sh
    build:
      context: .
      dockerfile: ./docker/DockerfileProto
    volumes:
      - .:/proto
  server:
    # command: ./server.sh
    command: ./scripts/server.sh
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - ./server:/go/src/meety_server
    ports:
      - "9090:9090"
    depends_on:
      - proto
  envoy:
    build:
      context: .
      dockerfile: DockerfileEnvoy
    ports:
      - "8080:8080"
    links:
      - server
  client:
    command: ./scripts/client.sh
    build:
      context: .
      dockerfile: DockerfileClient
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - proto
    ports:
      - "3000:3000"
    environment: 
      - EXTEND_ESLINT=true